apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  maxHistory: 2
  interval: 30m
  chart:
    spec:
      chart: crossplane
      version: "2.2.x"
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
      interval: 1h
  install:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
  values:
    provider:
      packages:
        - xpkg.upbound.io/scaleway/provider-scaleway:v0.6.0
      defaultActivations: []
    resourcesCrossplane:
      requests:
        memory: 384Mi
    resourcesRBACManager:
      requests:
        memory: 128Mi
    securityContextCrossplane:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContextRBACManager:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
