apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-store
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/system/base/external-dns
  prune: true
  wait: true
  postBuild:
    substitute:
      CLUSTER_NAME: ${CLUSTER_NAME}
