apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scaleway-crossplane-credentials
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: scaleway-crossplane-credentials
  data:
    - secretKey: credentials
      remoteRef:
        key: "name:scaleway-crossplane-credentials"
        version: latest_enabled
