apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/cert-manager-scaleway-webhook
  - ../base/envoy-gateway
  - ../base/external-secrets
patches:
  - path: envoy-gateway-patch.yaml
