apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/alloy
  - ../base/cert-manager
  - ../base/cert-manager-scaleway-webhook
  - ../base/cloudnative-pg
  - ../base/envoy-gateway
  - ../base/external-secrets
  - ../base/kube-prometheus-stack
  - ../base/loki
patches:
  - path: envoy-gateway-patch.yaml
