apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dns-manager.yaml
  - cnpg-backup.yaml
  - eso-reader.yaml
  - jeanne-genai.yaml
  - jeanne-registry.yaml
  - jeanne-release-registry.yaml
