apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- crashloop-deployment.yaml
- error-logger-deployment.yaml
- pending-deployment.yaml
- slow-traces-deployment.yaml
