apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scaleway-dns-credentials
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: scaleway-dns-credentials
  data:
    - secretKey: SCW_ACCESS_KEY
      remoteRef:
        key: "name:scaleway-dns-credentials"
        property: access-key
        version: latest_enabled
    - secretKey: SCW_SECRET_KEY
      remoteRef:
        key: "name:scaleway-dns-credentials"
        property: secret-key
        version: latest_enabled
