apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mistral-api-credentials
  namespace: jeanne
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: mistral-api-credentials
  data:
    - secretKey: MISTRAL_API_KEY
      remoteRef:
        key: "name:mistral-api-credentials"
        property: MISTRAL_API_KEY
        version: latest_enabled
