apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jeanne-scaleway-credentials
  namespace: jeanne
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: jeanne-scaleway-credentials
  data:
    - secretKey: SCW_ACCESS_KEY
      remoteRef:
        key: "name:jeanne-scaleway-credentials"
        property: SCW_ACCESS_KEY
        version: latest_enabled
    - secretKey: SCW_SECRET_KEY
      remoteRef:
        key: "name:jeanne-scaleway-credentials"
        property: SCW_SECRET_KEY
        version: latest_enabled
