apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jeanne-github-credentials
  namespace: jeanne
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: jeanne-github-credentials
  data:
    - secretKey: GITHUB_APP_ID
      remoteRef:
        key: "name:openclaw-github-app"
        property: APP_ID
        version: latest_enabled
    - secretKey: GITHUB_APP_INSTALLATION_ID
      remoteRef:
        key: "name:openclaw-github-app"
        property: INSTALLATION_ID
        version: latest_enabled
    - secretKey: GITHUB_APP_PRIVATE_KEY
      remoteRef:
        key: "name:openclaw-github-app"
        property: PRIVATE_KEY
        version: latest_enabled