apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jeanne-matrix-credentials
  namespace: jeanne
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: jeanne-matrix-credentials
  data:
    - secretKey: MATRIX_USER_ID
      remoteRef:
        key: "name:jeanne-matrix-credentials"
        property: MATRIX_USER_ID
        version: latest_enabled
    - secretKey: MATRIX_ACCESS_TOKEN
      remoteRef:
        key: "name:jeanne-matrix-credentials"
        property: MATRIX_ACCESS_TOKEN
        version: latest_enabled
