apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: jeanne-data-snapshot
  namespace: jeanne
  labels:
    app.kubernetes.io/name: jeanne
    app.kubernetes.io/instance: jeanne
    app.kubernetes.io/managed-by: flux-operator
spec:
  volumeSnapshotClassName: jeanne-data-snapshot-class
  source:
    persistentVolumeClaimName: jeanne-data