apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-s3-credentials
  namespace: matrix
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: cnpg-s3-credentials
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: "name:cnpg-s3-credentials"
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: "name:cnpg-s3-credentials"
        property: ACCESS_SECRET_KEY
