apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg-cluster-synapse.yaml
  - cnpg-cluster-mas.yaml
  - objectstore.yaml
  - scheduledbackup-synapse.yaml
  - scheduledbackup-mas.yaml
  - externalsecret-s3.yaml
