apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: matrix-synapse-backup
  namespace: matrix
spec:
  schedule: "0 0 0 * * *"
  cluster:
    name: matrix-synapse
  immediate: true
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: matrix-backup-store
