apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cockpit-query-token
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: cockpit-query-token
  data:
    - secretKey: token
      remoteRef:
        key: "name:cockpit-query-token"
        version: latest_enabled
