apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: scaleway-secret-store
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: "00000000-0000-0000-0000-000000000000"
      accessKey:
        secretRef:
          name: scaleway-credentials
          namespace: external-secrets
          key: access-key
      secretKey:
        secretRef:
          name: scaleway-credentials
          namespace: external-secrets
          key: secret-key
