apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  endpointSelector:
    matchLabels:
      app: crossplane
  egress:
    # DNS
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    # K8s API server
    - toEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: crossplane-rbac-manager
  namespace: crossplane-system
spec:
  endpointSelector:
    matchLabels:
      app: crossplane-rbac-manager
  egress:
    # DNS
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    # K8s API server
    - toEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: scaleway-provider
  namespace: crossplane-system
spec:
  endpointSelector:
    matchLabels:
      pkg.crossplane.io/provider: scaleway-provider-scaleway
  egress:
    # DNS
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    # K8s API server
    - toEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
    # Scaleway API (manages cloud resources)
    - toFQDNs:
        - matchName: "api.scaleway.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
