apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system
  namespace: flux-system
spec:
  interval: 10m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/system/dev
  prune: true
  wait: true
  postBuild:
    substitute:
      SCW_ORGANIZATION_ID: "b7b9a9bd-321d-4146-a793-ccb3d420d4c8"
      SCW_PROJECT_ID: "25485e2e-7a3a-40ae-8d0c-1496ef7c5e0f"
      SCW_REGION: "fr-par"
      CLUSTER_NAME: "dev"
      ACME_EMAIL: "lejeune.n@gmail.com"
      GOOGLE_OIDC_CLIENT_ID: "484522706079-b6vgq5v59u03nmhodubf1e57545gq9bs.apps.googleusercontent.com"
