apiVersion: object.scaleway.upbound.io/v1alpha1
kind: Bucket
metadata:
  name: cnpg-backups
spec:
  deletionPolicy: Orphan
  forProvider:
    name: scw-k8s-advanced-${CLUSTER_NAME}-cnpg-backups
    region: ${SCW_REGION}
    tags:
      env: ${CLUSTER_NAME}
      managed-by: crossplane
  providerConfigRef:
    name: default
