apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: scaleway-secret-store
spec:
  provider:
    scaleway:
      region: ${SCW_REGION}
      projectId: ${SCW_PROJECT_ID}
      accessKey:
        secretRef:
          name: scaleway-credentials
          namespace: external-secrets
          key: access-key
      secretKey:
        secretRef:
          name: scaleway-credentials
          namespace: external-secrets
          key: secret-key
