apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager-issuer
  - ../base/crossplane-config
  - ../base/envoy-gateway-config
  - ../base/external-secrets-store
patches:
  - path: envoy-gateway-patch.yaml
