apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matomo-admin-credentials
  namespace: matomo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: matomo-admin-credentials
  data:
    - secretKey: matomo-password
      remoteRef:
        key: "name:matomo-admin-credentials"
        property: matomo-password
        version: latest_enabled
