apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-credentials
  namespace: matomo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: mariadb-credentials
  data:
    - secretKey: password
      remoteRef:
        key: "name:matomo-mariadb-credentials"
        property: password
        version: latest_enabled
    - secretKey: root-password
      remoteRef:
        key: "name:matomo-mariadb-credentials"
        property: root-password
        version: latest_enabled
