apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg-cluster.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - configmap-db.yaml
  - externalsecret-s3.yaml
  - network-policy.yaml
