apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: s3-store
  namespace: wisdom
spec:
  configuration:
    destinationPath: s3://scw-k8s-advanced-${CLUSTER_NAME}-cnpg-backups-v2/
    endpointURL: https://s3.${SCW_REGION}.scw.cloud
    s3Credentials:
      accessKeyId:
        name: cnpg-s3-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-s3-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
  retentionPolicy: "3d"
