apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
        - name: dashy
          image: lissy93/dashy:3.1.12
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /app/user-data/conf.yml
              subPath: conf.yml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: dashy-config
