apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-oidc-client-secret
  namespace: dashy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: google-oidc-client-secret
  data:
    - secretKey: client-secret
      remoteRef:
        key: "name:google-oidc-credentials"
        property: client-secret
        version: latest_enabled
