apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matomo-token-auth
  namespace: wisdom
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: matomo-token-auth
  data:
    - secretKey: token
      remoteRef:
        key: "name:matomo-token-auth"
        property: token
        version: latest_enabled
