apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wisdom-api-auth-token
  namespace: wisdom
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-store
  target:
    name: wisdom-api-auth-token
  data:
    - secretKey: token
      remoteRef:
        key: "name:wisdom-api-auth-token"
        property: token
        version: latest_enabled
