# Deploys the app chart and overrides platform-specific values
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sovereign-cloud-wisdom
  namespace: wisdom
spec:
  interval: 30m
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: sovereign-cloud-wisdom
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: rg.fr-par.scw.cloud/sovereign-cloud-wisdom/sovereign-cloud-wisdom
      tag: "20260411161750-30f2a10" # {"$imagepolicy": "flux-system:sovereign-cloud-wisdom:tag"}
      pullSecret: sovereign-cloud-wisdom-registry
    podLabels:
      beyla.io/watch: "true"
    env:
      - name: OTEL_SERVICE_NAME
        value: sovereign-cloud-wisdom
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://alloy.monitoring.svc.cluster.local:4317
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: none
      - name: OTEL_LOGS_EXPORTER
        value: none
    database:
      secret: wisdom-db-app
    cloudProvider: scw-advanced
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
